if (NOT DEFINED VIDEO_OVEN_NATIVE_DIR)
    message(FATAL_ERROR "VIDEO_OVEN_NATIVE_DIR is required")
endif()

file(MAKE_DIRECTORY "${VIDEO_OVEN_NATIVE_DIR}")
file(GLOB VIDEO_OVEN_STALE_NATIVE_LIBS
    "${VIDEO_OVEN_NATIVE_DIR}/*.so"
    "${VIDEO_OVEN_NATIVE_DIR}/*.so.*"
    "${VIDEO_OVEN_NATIVE_DIR}/*.dylib"
    "${VIDEO_OVEN_NATIVE_DIR}/*.dll"
    "${VIDEO_OVEN_NATIVE_DIR}/libs.txt"
)

if (VIDEO_OVEN_STALE_NATIVE_LIBS)
    file(REMOVE ${VIDEO_OVEN_STALE_NATIVE_LIBS})
endif()
